#!/usr/bin/env bash

# Test what artist values are actually being generated by the main script
AUDIO_EXTENSIONS="*.mp3 *.flac *.wav *.aiff *.aif *.m4a *.ogg *.opus *.wma *.vdjstems"
SOURCE_DIR="/Users/johnnyclem/Desktop/Music/LPs"

# Copy the functions from main script (simplified)
extract_artist_album_from_folder() {
    local folder_path="$1"
    local folder_name
    folder_name=$(basename "$folder_path")
    
    local artist="Unknown Artist"
    local album="$folder_name"
    
    if [[ "$folder_name" =~ ^(.+)[[:space:]]*-[[:space:]]*(.+)$ ]]; then
        artist="${BASH_REMATCH[1]}"
        album="${BASH_REMATCH[2]}"
    else
        artist="$folder_name"
    fi
    
    echo "$artist|$album"
}

has_audio_files() {
    local dir="$1"
    local ext
    for ext in $AUDIO_EXTENSIONS; do
        if find "$dir" -maxdepth 1 -type f -iname "$ext" -quit 2>/dev/null; then
            return 0
        fi
    done
    return 1
}

has_audio_subdirectories() {
    local dir="$1"
    local subdir
    while IFS= read -r -d '' subdir; do
        if has_audio_files "$subdir"; then
            return 0
        fi
    done < <(find "$dir" -mindepth 1 -maxdepth 1 -type d -print0 2>/dev/null)
    return 1
}

analyze_directory_structure() {
    local filepath="$1"
    local dir
    dir=$(dirname "$filepath")
    local parent_dir
    parent_dir=$(dirname "$dir")
    
    if [[ "$parent_dir" != "$SOURCE_DIR" ]] && has_audio_subdirectories "$parent_dir"; then
        echo "multi_album"
    elif has_audio_files "$dir"; then
        echo "single_album"
    else
        echo "unknown"
    fi
}

get_album_context() {
    local filepath="$1"
    local dir
    dir=$(dirname "$filepath")
    local structure
    structure=$(analyze_directory_structure "$filepath")
    
    case "$structure" in
        "multi_album")
            local parent_dir artist album
            parent_dir=$(dirname "$dir")
            album_context=$(extract_artist_album_from_folder "$parent_dir")
            artist="${album_context%%|*}"
            album=$(basename "$dir")
            ;;
        "single_album")
            album_context=$(extract_artist_album_from_folder "$dir")
            artist="${album_context%%|*}"
            album="${album_context##*|}"
            ;;
        *)
            artist="Unknown Artist"
            album="Unknown Album"
            ;;
    esac
    
    echo "$artist|$album"
}

echo "Testing first 10 files and their generated artists:"
echo ""

# Get first 10 files
temp_files_list=$(mktemp)
find "$SOURCE_DIR" -type f -iname "*.flac" | head -10 > "$temp_files_list"

count=0
while IFS= read -r file; do
    ((count++))
    echo "File $count: $(basename "$file")"
    dir=$(dirname "$file")
    echo "  Directory: $dir"
    
    context=$(get_album_context "$file")
    artist="${context%%|*}"
    album="${context##*|}"
    echo "  Generated Artist: '$artist'"
    echo "  Generated Album: '$album'"
    echo ""
done < "$temp_files_list"

rm -f "$temp_files_list"